### ISSUE TITLE
Cannot add integration after installing repo

### ISSUE THREAD

**Issue by amatsoukas** [siku2/hass-weatherlink#16]
I am not sure if i am doing something wrong, but i am unable to find the Weatherlink integration to install in home assistant.

I added the custom repo in HACS, and restarted HA. It shows as installed afterwards (version 0.5.1)

Then i am going in Configuration > Integrations, click on "ADD" and i cannot find the Weatherlink Integration

I am running Home Assistant 2021.10.6

**Comment by siku2** [comment]
Did you only _add_ the custom repository, or did you also install the integration in HACS? These are two separate steps.

**Comment by amatsoukas** [comment]
I tried to install the integration, but it was not showing. However, it seems that after installing the repo, it took a couple of hours for the integration to appear in the list of available integration. Not sure why.

Nevertheless, i just installed the integration and everything appears to be working fine!

Thank you!
