### ISSUE TITLE
custom_components.weatherlink.weather::Weather is overriding deprecated methods on an instance of WeatherEntity

### ISSUE THREAD

**Issue by RhizomaticNomad** [siku2/hass-weatherlink#25]
Please fix this!
Thanks a lot in advance!

Logger: homeassistant.components.weather
Source: components/weather/__init__.py:308
Integration: Weather (documentation, issues)
First occurred: 3:46:49 PM (1 occurrences)
Last logged: 3:46:49 PM
custom_components.weatherlink.weather::Weather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author.

It's probably related to https://developers.home-assistant.io/blog/2022/06/27/weather_entity_refactoring/

And maybe also solves https://github.com/siku2/hass-weatherlink/issues/24

**Comment by shtrom** [comment]
Another warning due to a similar refactor

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 17:00:59 (1 occurrences)
Last logged: 17:00:59

Detected integration that accesses the `name` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for weatherlink using this method at custom_components/weatherlink/units.py, line 213: if hass.config.units.name == CONF_UNIT_SYSTEM_IMPERIAL:
```
