### ISSUE TITLE
Instructions switching the Units of Measurements

### ISSUE THREAD

**Issue by NRutt2005** [siku2/hass-weatherlink#4]
@siku2 This is a great improvement to this integration. My only question would be, could you add instructions on where to switch the unit of measurements for each sensor within the code? Thank you again!

**Comment by siku2** [comment]
Why do you want to adjust the units in the code?

**Comment by MichaelNMaggs** [comment]
I can't speak for NRutt2005, but it actually took me some time after installing the upgrade to work out why I wasn't able to find the new unit options.  I hadn't read the instructions carefully enough, and was expecting them to appear on the HACS card, not on the configuation page card.  Perhaps that could be stressed in the instructions? (or perhaps I should just read things more carefully ?)

**Comment by siku2** [comment]
This isn't something I considered documenting because it's not something that's particular to this integration. That's just how Home Assistant works as a whole.
Here's an idea though, I opened up the [Repository Wiki](https://github.com/siku2/hass-weatherlink/wiki) so anyone can edit it.
I lack the "outsider perspective" to document all the details in a beginner-friendly way.

**Comment by NRutt2005** [comment]
@siku2 @MichaelNMaggs I guess my problem is I'm not finding an "Instructions" section. I am also not seeing anything in the configuration page card for switching the units of measurements. That is the only reason I thought I would need to do the switching of units in the code. For an example of what I am wanting to do. Currently after loading the integration, the pressure is showing in PSI and I want to see this in inches Hg. All I see in the configure section of the card is the update interval. I've attached a photo of what I'm seeing. Maybe I am completely missing the mark on where to do the configuration changes or even to find the instructions. Sorry for the trouble. 
<img width="1680" alt="Screen Shot 2021-05-28 at 3 37 13 PM" src="https://user-images.githubusercontent.com/75466468/120040359-fbe09d80-bfcb-11eb-9d59-348153499fc2.png">

**Comment by NRutt2005** [comment]
i just happened to submit the update interval and it took me to the units of measurement configuration page. Sorry for the trouble. I still don't see the instructions part of the integration but I managed to click around enough to figure out how to change the configuration of unit of measurements settings. Thanks @siku2 and @MichaelNMaggs

**Comment by siku2** [comment]
> I still don't see the instructions part of the integration but I managed to click around enough to figure out how to change the configuration of unit of measurements settings. 

Again, please feel encouraged to help out by documenting your findings in the [Wiki](https://github.com/siku2/hass-weatherlink/wiki).

**Comment by MichaelNMaggs** [comment]
Yes, I see the problem. I agree that it would be better to have a direct visible link to the unit configurations rather than having them appear only after hitting submit on the update interval dialogue box. That does make the unit options somewhat invisible!

**Comment by siku2** [comment]
As far as I'm aware, this isn't possible, unfortunately.
I did try to make it easier to tell that there are multiple config "pages" in version 0.4.0 though.

**Comment by MichaelNMaggs** [comment]
OK. Could the text on the dialogue box perhaps isay something like "To access other options including rounding and units, click on the submit button" ?

**Comment by siku2** [comment]
It could, yes. The description can be changed here:
https://github.com/siku2/hass-weatherlink/blob/e1d8a7bf0aea90db43b2f37d6b4fbfefea3495bd/custom_components/weatherlink/translations/en.json#L24-L30

**Comment by NRutt2005** [comment]
I've updated the wiki page for this integration to explain how to update the refresh interval and the units of measurement. Thank you @siku2 and @MichaelNMaggs

**Comment by siku2** [comment]
> I've updated the wiki page for this integration to explain how to update the refresh interval and the units of measurement.

Awesome, thanks!

**Comment by MichaelNMaggs** [comment]
@siku2 thanks for your great work with this.
