### ISSUE TITLE
No headings in rounding dialogue box

### ISSUE THREAD

**Issue by MichaelNMaggs** [siku2/hass-weatherlink#6]
Many thanks for adding the rounding options. Just one small thing: the dialogue box doesn't show any headings:

<img width="425" alt="Screenshot 2021-05-29 at 18 08 32" src="https://user-images.githubusercontent.com/9252387/120078851-4be16200-c0a9-11eb-99d9-9e235f2ca2bc.png">

**Comment by siku2** [comment]
That's a caching issue. You just need to reload your page (might even require a force-reload) to fix it.

**Comment by MichaelNMaggs** [comment]
Right, yes, that does it. Thanks
